version: '3.7'

services:
  server:
    build:
      context: .
      target: server-dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app:delegated
      - node_modules_server:/app/node_modules
    environment:
      - MONGO_URI="mongodb://mongodb:27017"
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GOOGLE_CLIENT=${GOOGLE_CLIENT}
    healthcheck:
      disable: true
    networks:
      - uptime-monitor

  client:
    build:
      context: .
      target: client-dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app:delegated
      - node_modules_client:/app/node_modules
    environment:
      - REACT_APP_API=${REACT_APP_API}
      - REACT_APP_GOOGLE_CLIENT=${REACT_APP_GOOGLE_CLIENT}
    healthcheck:
      disable: true
    networks:
      - uptime-monitor

  mongodb:
    image : mongo:4.4.8
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
    - 27017:27017
    networks:
      - uptime-monitor
    restart: unless-stopped

networks:
  uptime-monitor:

volumes:
  mongodb-data:
    driver: local
  node_modules_server:
    driver: local
  node_modules_client:
    driver: local