{{- if (include "uptime-monitor.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-monitor.fullname" . }}
  labels:
    {{- include "uptime-monitor.labels" . | nindent 4 }}
type: Opaque
data:
  mongoUri:  {{ .Values.mongoUri | toString | b64enc | quote }}
{{- end }}