  
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uptime-web.serviceAccountName" . }}
  labels:
{{ include "uptime-web.labels" . | nindent 4 }}
{{- end -}}