name: Node.js Server CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  TERM: xterm

jobs:
  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup using Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Run NPM Install
        working-directory: ./server
        run: npm install

      - name: Setup Jest
        working-directory: ./server
        run: npm install jest -g

      - name: Run NPM Tests
        id: npm-tests
        working-directory: ./server
        run: npm test
