name: Node.js Server CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  TERM: xterm

jobs:
  test-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup using Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Move to Server directory
        run: cd server

      - name: Run NPM Install
        run: npm install

      - name: Run NPM Tests
        id: npm-tests
        run: npm test
